/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-detection_estimation
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DETECTION_ESTIMATION_API_H
#define INCLUDED_DETECTION_ESTIMATION_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_detection_estimation_EXPORTS
#define DETECTION_ESTIMATION_API __GR_ATTR_EXPORT
#else
#define DETECTION_ESTIMATION_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DETECTION_ESTIMATION_API_H */
